version: "3.8"
services:
  dev-lab:
    image: hakimr/dev-lab
    command: tail -f /dev/null # Keep it alive !
    ports:
      - "7000-7005:7000-7005"
    volumes:
      - /home/hakim/Projects:/Projects # Adjust this to your needs

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    # volumes:
    # - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: hydra
    ports:
      - "8080:8080"

#volumes:
#  db_data:
