# should go in ~/.config
[ui]
width=2400
height=1400
font_path=/home/hakim/.fonts/Cousine/CousineNerdFontMono-Regular.ttf
scale=1.6
font_size_interface=16
font_size_code=18
layout=v(75,h(80,Source,v(50,t(Breakpoints,Exe,Commands,Struct),t(Stack,Files,Thread,CmdSearch))),h(65,Console,t(Watch,Locals,Registers,Data,Prof,Memory,View)))
selectable_source=1
